version: '3'

tasks:
  build_ui:
    desc: "Build and flash the web UI to the ESP32"
    dir: client
    cmds:
    - npm install
    - npx vite build
    - gzip ./dist/index.html
    - cp ./dist/index.html.gz ../data/
  
  upload_fs:
    desc: "Upload the data folder to ESP32 SPIFFS"
    cmds:
    - pio run --target buildfs --environment seeed_xiao_esp32s3
    - pio run --target uploadfs --environment seeed_xiao_esp32s3

  upload_ui:
    desc: "Upload the web UI to the ESP32"
    cmds:
    - task: build_ui
    - task: upload_fs
  
  upload_firmware:
    desc: "Upload the firmware to the ESP32"
    cmds:
    - pio run --target upload --environment seeed_xiao_esp32s3

  upload:
    desc: "Upload the web UI and firmware to the ESP32"
    cmds:
    - task: upload_ui
    - task: upload_firmware

  ota_firmware_upload:
    desc: "Upload the firmware to the ESP32 using OTA"
    cmds:
    - pio run --target upload --environment seeed_xiao_esp32s3 --upload-port esp32doorbell.local