version: '3.8'

services:
  label-studio:
    container_name: label-studio
    image: heartexlabs/label-studio:latest
    ports:
      - "8089:8080"
    volumes:
      - ./mydata:/label-studio/data
    env_file:
      - .env
    stdin_open: true
    tty: true
